## ENMO calculation 
The Euclidean Norm Minus One (ENMO) is calculated from the three acceleration axes (x, y, z):

ENMO = √(x² + y² + z²) - 1

A function is defined to make the ENMO calculation reusable and easier to apply to the acceleration data.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df= pd.read_csv("0_z.csv", comment="#")
df.head()

      t       x       y       z
0  0.00 -0.0938 -0.0156  0.9531
1  0.02 -0.0938 -0.0156  0.9531
2  0.04 -0.0938 -0.0156  0.9531
3  0.06 -0.0938 -0.0156  0.9531
4  0.08 -0.0938 -0.0156  0.9531

In [10]:
dt = df["t"].iloc[1]- df["t"].iloc[0]
fs = 1/dt

In [5]:
def calculate_enmo(x, y, z):
    return np.sqrt(x**2 + y**2 + z**2) - 1

In [6]:
df["enmo"] = calculate_enmo(df["x"], df["y"], df["z"])

In [7]:
df[["t", "enmo"]].head()

      t      enmo
0  0.00 -0.042168
1  0.02 -0.042168
2  0.04 -0.042168
3  0.06 -0.042168
4  0.08 -0.042168

In [8]:
def calculate_integrated_enmo(df, epoch, fs):
    # Nombre d'échantillons par epoch
    samples = int(fs * epoch)

    # ENMO intégré
    integrated_enmo = (
        df["enmo"]
        .groupby(df.index // samples)
        .sum()
        * epoch / 60
    )

    return integrated_enmo

In [11]:
integrated_enmo_10s = calculate_integrated_enmo(df, 10, fs)
integrated_enmo_30s = calculate_integrated_enmo(df, 30, fs)
integrated_enmo_60s = calculate_integrated_enmo(df, 60, fs)

print("Number of 10 s epochs:", len(integrated_enmo_10s))
print("Number of 30 s epochs:", len(integrated_enmo_30s))
print("Number of 60 s epochs:", len(integrated_enmo_60s))

Number of 10 s epochs: 42
Number of 30 s epochs: 14
Number of 60 s epochs: 7